version: "3.9"

services:
    db: 
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST_AUTH_METHOD=trust
            
    client:
        build: .
        volumes:
            - .:/store
        command: tail -F anything
